// source: proto/ds.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var proto_dsmap_pb = require('../proto/dsmap_pb.js');
goog.object.extend(proto, proto_dsmap_pb);
goog.exportSymbol('proto.ds.proto.AuthError', null, global);
goog.exportSymbol('proto.ds.proto.DSError', null, global);
goog.exportSymbol('proto.ds.proto.DSError.EventCase', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ds.proto.AuthError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ds.proto.AuthError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ds.proto.AuthError.displayName = 'proto.ds.proto.AuthError';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ds.proto.DSError = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.ds.proto.DSError.oneofGroups_);
};
goog.inherits(proto.ds.proto.DSError, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ds.proto.DSError.displayName = 'proto.ds.proto.DSError';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ds.proto.AuthError.prototype.toObject = function(opt_includeInstance) {
  return proto.ds.proto.AuthError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ds.proto.AuthError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ds.proto.AuthError.toObject = function(includeInstance, msg) {
  var f, obj = {
    message: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ds.proto.AuthError}
 */
proto.ds.proto.AuthError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ds.proto.AuthError;
  return proto.ds.proto.AuthError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ds.proto.AuthError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ds.proto.AuthError}
 */
proto.ds.proto.AuthError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMessage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ds.proto.AuthError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ds.proto.AuthError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ds.proto.AuthError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ds.proto.AuthError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessage();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string message = 1;
 * @return {string}
 */
proto.ds.proto.AuthError.prototype.getMessage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.ds.proto.AuthError} returns this
 */
proto.ds.proto.AuthError.prototype.setMessage = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};



/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.ds.proto.DSError.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.ds.proto.DSError.EventCase = {
  EVENT_NOT_SET: 0,
  AUTH_ERROR: 1
};

/**
 * @return {proto.ds.proto.DSError.EventCase}
 */
proto.ds.proto.DSError.prototype.getEventCase = function() {
  return /** @type {proto.ds.proto.DSError.EventCase} */(jspb.Message.computeOneofCase(this, proto.ds.proto.DSError.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ds.proto.DSError.prototype.toObject = function(opt_includeInstance) {
  return proto.ds.proto.DSError.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ds.proto.DSError} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ds.proto.DSError.toObject = function(includeInstance, msg) {
  var f, obj = {
    authError: (f = msg.getAuthError()) && proto.ds.proto.AuthError.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ds.proto.DSError}
 */
proto.ds.proto.DSError.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ds.proto.DSError;
  return proto.ds.proto.DSError.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ds.proto.DSError} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ds.proto.DSError}
 */
proto.ds.proto.DSError.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.ds.proto.AuthError;
      reader.readMessage(value,proto.ds.proto.AuthError.deserializeBinaryFromReader);
      msg.setAuthError(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ds.proto.DSError.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ds.proto.DSError.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ds.proto.DSError} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ds.proto.DSError.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getAuthError();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.ds.proto.AuthError.serializeBinaryToWriter
    );
  }
};


/**
 * optional AuthError auth_error = 1;
 * @return {?proto.ds.proto.AuthError}
 */
proto.ds.proto.DSError.prototype.getAuthError = function() {
  return /** @type{?proto.ds.proto.AuthError} */ (
    jspb.Message.getWrapperField(this, proto.ds.proto.AuthError, 1));
};


/**
 * @param {?proto.ds.proto.AuthError|undefined} value
 * @return {!proto.ds.proto.DSError} returns this
*/
proto.ds.proto.DSError.prototype.setAuthError = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.ds.proto.DSError.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.ds.proto.DSError} returns this
 */
proto.ds.proto.DSError.prototype.clearAuthError = function() {
  return this.setAuthError(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ds.proto.DSError.prototype.hasAuthError = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.ds.proto);
