#!/usr/bin/env bash

GIT_DIR=$(git rev-parse --show-toplevel)
cd ${GIT_DIR}
trap "cd ${GIT_DIR}" err exit

# OUT_DIR=${1:-./}

# # generate javascript
# ./node_modules/.bin/pbjs -t static-module -o ${OUT_DIR}/gen.js proto/*
# # add typescript types
# ./node_modules/.bin/pbts -o ${OUT_DIR}/gen.d.ts ${OUT_DIR}/gen.js

OUT_DIR="./src/"
TS_OUT_DIR="./src/"
IN_DIR="./proto"
PROTOC="$(npm bin)/grpc_tools_node_protoc"
PROTOC_GEN_TS_PATH="$(npm bin)/protoc-gen-ts"
PROTOC_GEN_GRPC_PATH="$(npm bin)/grpc_tools_node_protoc_plugin"

$PROTOC \
    -I="./" \
    --plugin=protoc-gen-ts=$PROTOC_GEN_TS_PATH \
    --plugin=protoc-gen-grpc=$PROTOC_GEN_GRPC_PATH \
    --js_out=import_style=commonjs:$OUT_DIR \
    --grpc_out=grpc_js:$OUT_DIR \
    --ts_out=service=grpc-node,mode=grpc-js:$TS_OUT_DIR \
    "$IN_DIR"/*.proto